[project]
name = "predator-prey-sbi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.9.0",
    "numpy>=2.0.0",
    "pyyaml>=6.0.2",
    "sbi>=0.22.0",
    "scipy>=1.13.0",
    "torch>=2.9.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
